excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ashubits.github.io
name: TalktoAshuSharma
description: This blog is to help young and fresh minds so often found in academia; interested in the area of Malware analysis.
author: Ashu Sharma
avatar: http://www.gravatar.com/avatar/ashusharma
ga_domain: 
ga_tracking_id: 